Class {
	#name : #FamixOpenstackSourceLanguage,
	#superclass : #FamixOpenstackEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Openstack-Entities-Entities'
}

{ #category : #meta }
FamixOpenstackSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixOpenstackEntity>
	<package: #'Openstack-Entities'>
	<generated>
	^self
]
