Class {
	#name : #FamixHOTSourceTextAnchor,
	#superclass : #FamixHOTSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Openstack-Entities-Entities'
}

{ #category : #meta }
FamixHOTSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixHOTSourceAnchor>
	<package: #'Openstack-Entities'>
	<generated>
	^self
]
