Class {
	#name : #FamixOpenstackSourceTextAnchor,
	#superclass : #FamixOpenstackSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Openstack-Entities-Entities'
}

{ #category : #meta }
FamixOpenstackSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixOpenstackSourceAnchor>
	<package: #'Openstack-Entities'>
	<generated>
	^self
]
