Class {
	#name : #FamixOpenstackModel,
	#superclass : #MooseModel,
	#category : #'Openstack-Entities-Model'
}

{ #category : #accessing }
FamixOpenstackModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixOpenstackModel class >> annotation [
	<FMClass: #FamixOpenstackModel super: #MooseModel>
	<package: #'Openstack-Entities'>
	<generated>
]
