Class {
	#name : #FamixHOTUnknownSourceLanguage,
	#superclass : #FamixHOTSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Openstack-Entities-Entities'
}

{ #category : #meta }
FamixHOTUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixHOTSourceLanguage>
	<package: #'Openstack-Entities'>
	<generated>
	^self
]
