Class {
	#name : #FamixOpenstackOpenStackEntity,
	#superclass : #FamixOpenstackEntity,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Openstack-Entities-Entities'
}

{ #category : #meta }
FamixOpenstackOpenStackEntity class >> annotation [

	<FMClass: #OpenStackEntity super: #FamixOpenstackEntity>
	<package: #'Openstack-Entities'>
	<generated>
	^self
]
