Class {
	#name : #FamixOpenstackUnknownSourceLanguage,
	#superclass : #FamixOpenstackSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Openstack-Entities-Entities'
}

{ #category : #meta }
FamixOpenstackUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixOpenstackSourceLanguage>
	<package: #'Openstack-Entities'>
	<generated>
	^self
]
